name: Git as GitHub Actions Bot
description: Set git config's user as GitHub Actions bot
branding:
  icon: git-commit
  color: orange
inputs:
  config-level:
    description: git config's level
    required: false
    default: 'local'
    type: choice
    options:
      - system
      - global
      - local
runs:
  using: composite
  steps:
    - run: |
        git config --$LEVEL user.email "github-actions[bot]@users.noreply.github.com"
        git config --$LEVEL user.name "github-actions[bot]"
      env:
        LEVEL: ${{ inputs.config-level }}
      shell: bash
